export const FETCH_ORGANISATION_REQUEST = "FETCH_ORGANISATION_REQUEST";
export const FETCH_ORGANISATION_SUCCESS = "FETCH_ORGANISATION_SUCCESS";
export const FETCH_ORGANISATION_FAILURE = "FETCH_ORGANISATION_FAILURE";
