export const FETCH_APPARTEMENTS_REQUEST = "FETCH_APPARTEMENTS_REQUEST";
export const FETCH_APPARTEMENTS_SUCCESS = "FETCH_APPARTEMENTS_SUCCESS";
export const FETCH_APPARTEMENTS_FAILURE = "FETCH_APPARTEMENTS_FAILURE";